//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unity.VisualScripting.Generated.PropertyProviders
{
	
	
	[global::Unity.VisualScripting.SerializedPropertyProviderAttribute(typeof(global::Carrot.On_Action_where_online))]
	public class PropertyProvider_Carrot_On_Action_where_online : Unity.VisualScripting.SerializedPropertyProvider<Carrot.On_Action_where_online>
	{
	}
}
